on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
    
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    ## create application-prod.yml
    - name: make application-prod.yml
      run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.yml
          echo '${{ secrets.YML_PROD }}' > ./application.yml
      shell: bash

    ## grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew


    ## gradle build
    - name: Build with Gradle
      run: ./gradlew build -x test

    ## docker build & push to production
    - name: Docker build & push to prod
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/sivil5 .
          docker push ${{ secrets.DOCKER_REPO }}/sivil5

    ## deploy to production
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      id: deploy-prod
      with:
        host: ${{ secrets.HOST_EC2 }} # EC2 퍼블릭 IPv4 DNS
        username: ubuntu
        key: ${{ secrets.PEM_KEY }}
        envs: GITHUB_SHA
        script: |
          sudo docker stop sivil5
          sudo docker rm sivil5
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/sivil5
          sudo docker run -d —name sivil5 -p 8080:8080 —network spharos45 ${{ secrets.DOCKER_USERNAME }}/sivil5
          sudo docker image prune -f
